spring.application.name=To-Do
server.port=${PORT:8080}

spring.datasource.url={DB_URL: jdbc:postgresql://ep-orange-scene-ah4ymlyo-pooler.c-3.us-east-1.aws.neon.tech:5432/To-Do}
spring.datasource.username={DB_USERNAME: neondb_owner}
spring.datasource.password={DB_PASSWORD: }
